// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARIPRh1f3G31PaXd4F5vqQuQH1yjyLwG0',
    appId: '1:667327318779:web:ae60fac0508475ee907e5e',
    messagingSenderId: '667327318779',
    projectId: 'official-console',
    authDomain: 'official-console.firebaseapp.com',
    databaseURL: 'https://official-console-default-rtdb.firebaseio.com',
    storageBucket: 'official-console.appspot.com',
    measurementId: 'G-NZWJ7DSYZ3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmrm-dy2Q67VGToBzDb9_CRu6jeDGtcoM',
    appId: '1:667327318779:android:1c36f12ffab19472907e5e',
    messagingSenderId: '667327318779',
    projectId: 'official-console',
    databaseURL: 'https://official-console-default-rtdb.firebaseio.com',
    storageBucket: 'official-console.appspot.com',
  );

  /*static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgGmP9X5dWA_YfyIzM089h8rrMt_0yS30',
    appId: '1:667327318779:ios:fcb92e23a7faf4b5907e5e',
    messagingSenderId: '667327318779',
    projectId: 'official-console',
    databaseURL: 'https://official-console-default-rtdb.firebaseio.com',
    storageBucket: 'official-console.appspot.com',
    androidClientId: '667327318779-1df0tca6a31k7h367uvhn2sfmka84vas.apps.googleusercontent.com',
    iosClientId: '667327318779-1rr1av9h4hl6170f3fkg74d15of9lgln.apps.googleusercontent.com',
    iosBundleId: 'com.evs.dev.pludin',
  );*/

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLqjRriCqIx6C2Vc3xa82AX3D7lz4cvyY',
    appId: '1:7956547599:ios:002d23d8b7b1aeabb5bb7a',
    messagingSenderId: '7956547599',
    projectId: 'pludin-45e87',
    databaseURL: 'https://pludin-45e87-default-rtdb.firebaseio.com',
    storageBucket: 'pludin-45e87.appspot.com',
    androidClientId:
        '7956547599-d4a7sja4326v5du9oel0o98pti0l1drj.apps.googleusercontent.com',
    iosClientId:
        '7956547599-d4a7sja4326v5du9oel0o98pti0l1drj.apps.googleusercontent.com',
    iosBundleId: 'com.evs.prod.pludin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgGmP9X5dWA_YfyIzM089h8rrMt_0yS30',
    appId: '1:667327318779:ios:7bf7df1859e8c9f5907e5e',
    messagingSenderId: '667327318779',
    projectId: 'official-console',
    databaseURL: 'https://official-console-default-rtdb.firebaseio.com',
    storageBucket: 'official-console.appspot.com',
    androidClientId:
        '667327318779-1df0tca6a31k7h367uvhn2sfmka84vas.apps.googleusercontent.com',
    iosClientId:
        '667327318779-q8ldcesplfts6etan29id6cfqugko5tk.apps.googleusercontent.com',
    iosBundleId: 'com.example.pludin',
  );
}
